/* MKT Colorado local search index. Add new listings here as town pages grow. */
window.MKT_SEARCH_INDEX = [
{name:'Cheese Importers',town:'Longmont',type:'business',category:'Shopping, Food & Drink',keywords:'cheese specialty market food gifts european shopping',url:'longmont.html#cheese-importers'},
{name:'Barbed Wire Books',town:'Longmont',type:'business',category:'Shopping',keywords:'bookstore books book shop new used books western americana author events reading',url:'longmont.html#barbed-wire-books'},
{name:'Juniper Goods',town:'Longmont',type:'business',category:'Shopping, Food & Drink, Local Makers',keywords:'boutique coffee zero proof bar gifts colorado makers shopping',url:'longmont.html#juniper-goods'},
{name:'Maker General',town:'Longmont',type:'business',category:'Shopping, Classes & Experiences, Local Makers',keywords:'sewing mending craft supplies workshops classes maker shop',url:'longmont.html#maker-general'},
{name:'Magic Fairy Candles',town:'Longmont',type:'business',category:'Shopping, Local Makers',keywords:'candles aromatics apothecary gifts handmade colorado made',url:'longmont.html#magic-fairy-candles'},
{name:'The Flower Bin',town:'Longmont',type:'business',category:'Shopping, Outdoors',keywords:'garden plants greenhouse flowers gifts nursery gardening',url:'longmont.html#the-flower-bin'},
{name:'Tumbleweed Art Collective',town:'Longmont',type:'business',category:'Shopping, Arts & Culture, Classes & Experiences, Local Makers',keywords:'art artisan boutique artists studios classes creative gifts',url:'longmont.html#tumbleweed-art-collective'},
{name:'Adorn Home & Gift Gallery',town:'Longmont',type:'business',category:'Shopping',keywords:'home decor gifts gallery furnishings house decorating rug rugs',url:'longmont.html#adorn-home-gift-gallery'},
{name:'TinkerMill',town:'Longmont',type:'place',category:'Classes & Experiences, Local Makers, Arts & Culture',keywords:'makerspace woodworking lasers blacksmithing robotics ceramics stained glass classes make create',url:'longmont.html#tinkermill'},
{name:'Crackpots Pottery Studio',town:'Longmont',type:'business',category:'Classes & Experiences, Arts & Culture, Family & Kids',keywords:'pottery paint ceramics creative classes art family kids',url:'longmont.html#crackpots-pottery-studio'},
{name:'Atomic Goblin Games',town:'Longmont',type:'business',category:'Shopping, Family & Kids, Movies & Entertainment',keywords:'board games tabletop gaming cards games entertainment shop',url:'longmont.html#atomic-goblin-games'},
{name:'Firehouse Art Center',town:'Longmont',type:'place',category:'Arts & Culture, Classes & Experiences',keywords:'art gallery exhibitions classes events contemporary art culture',url:'longmont.html#firehouse-art-center'},
{name:'Longmont Climbing Collective',town:'Longmont',type:'business',category:'Outdoors, Classes & Experiences',keywords:'climbing gym rock climbing auto belay fitness indoor outdoor',url:'longmont.html#longmont-climbing-collective'},
{name:'Mile-Hi Skydiving Center',town:'Longmont',type:'business',category:'Outdoors, Classes & Experiences',keywords:'skydiving skydive adventure thrill parachute',url:'longmont.html#mile-hi-skydiving-center'},
{name:'Wells Athletics Batting Cages',town:'Longmont',type:'business',category:'Family & Kids, Classes & Experiences',keywords:'baseball softball batting cages pitching machines indoor sports',url:'longmont.html#wells-athletics-batting-cages'},
{name:'Sunflower Farm',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids, Classes & Experiences',keywords:'farm animals nature music farmfest kids family educational',url:'longmont.html#sunflower-farm'},
{name:'YA YA Farm & Orchard',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids, Shopping',keywords:'farm orchard apples u-pick animals farm stand applefest family',url:'longmont.html#ya-ya-farm-orchard'},
{name:'The Bee Hugger Farm',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids',keywords:'farm animals bees pony rides sunflowers pumpkins kids family',url:'longmont.html#the-bee-hugger-farm'},
{name:'Ollin Farms',town:'Longmont',type:'place',category:'Farms & Animals, Food & Drink, Shopping',keywords:'farm regenerative agriculture farm stand csa dinners education produce',url:'longmont.html#ollin-farms'},
{name:'Aspen Moon Farm',town:'Longmont',type:'place',category:'Farms & Animals, Food & Drink, Shopping',keywords:'organic farm biodynamic csa roadside farm stand produce',url:'longmont.html#aspen-moon-farm'},
{name:'Rocky Mountain Pumpkin Ranch',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids, Events',keywords:'pumpkin patch fall festival farm organic produce family kids seasonal',url:'longmont.html#rocky-mountain-pumpkin-ranch'},
{name:'Good Life Refuge — Kindness Tours',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids, Classes & Experiences',keywords:'animal sanctuary rescued farm animals guided tours kindness family kids',url:'longmont.html#good-life-refuge-kindness-tours'},
{name:'Colorado Horse Rescue',town:'Longmont',type:'place',category:'Farms & Animals, Family & Kids',keywords:'horses horse rescue tours animals education visitors',url:'longmont.html#colorado-horse-rescue'},
{name:'Agricultural Heritage Center',town:'Longmont',type:'place',category:'History, Farms & Animals, Family & Kids',keywords:'historic farm museum barns farmhouse livestock agricultural history free',url:'longmont.html#agricultural-heritage-center',cost:'free'},
{name:'Historic Hoverhome',town:'Longmont',type:'place',category:'History, Arts & Culture',keywords:'historic mansion architecture history national register hover',url:'longmont.html#historic-hoverhome'},
{name:'Hover Farmstead',town:'Longmont',type:'place',category:'History, Farms & Animals',keywords:'historic farmstead agriculture farming heritage history',url:'longmont.html#hover-farmstead'},
{name:'Old Mill Park',town:'Longmont',type:'place',category:'History, Outdoors, Family & Kids',keywords:'historic park pioneer cabins milk house history outdoor free',url:'longmont.html#old-mill-park',cost:'free'},
{name:"Old St. Stephen's Church",town:'Longmont',type:'place',category:'History, Arts & Culture',keywords:'historic church landmark architecture national register history',url:'longmont.html#old-st-stephens-church'},
{name:'Longmont Museum',town:'Longmont',type:'place',category:'History, Arts & Culture, Family & Kids',keywords:'museum history art culture exhibitions programs family',url:'longmont.html#longmont-museum'},
{name:'Golden Ponds Nature Area',town:'Longmont',type:'place',category:'Outdoors, Family & Kids',keywords:'ponds trails hiking walking nature longs peak views fishing free park',url:'longmont.html#golden-ponds-nature-area',cost:'free'},
{name:'McIntosh Lake Nature Area',town:'Longmont',type:'place',category:'Outdoors, Water Activities, Family & Kids',keywords:'lake kayaking kayak paddleboard paddleboarding water trails walking mountain views boating free',url:'longmont.html#mcintosh-lake-nature-area',cost:'free'},
{name:'Union Reservoir Nature Area',town:'Longmont',type:'place',category:'Outdoors, Water Activities, Family & Kids',keywords:'reservoir boating fishing paddleboard paddleboarding swimming swim beach dog beach kayak kayaking water',url:'longmont.html#union-reservoir-nature-area'},
{name:'Sandstone Ranch',town:'Longmont',type:'place',category:'Outdoors, Family & Kids, History',keywords:'park playground recreation nature history trails family kids free',url:'longmont.html#sandstone-ranch',cost:'free'},
{name:'Sandstone Ranch Visitors & Learning Center',town:'Longmont',type:'place',category:'History, Outdoors, Family & Kids',keywords:'historic homestead nature exhibits wildlife learning family kids',url:'longmont.html#sandstone-ranch-visitors-learning-center'},
{name:'Dickens Farm Nature Area',town:'Longmont',type:'place',category:'Outdoors, Water Activities, Family & Kids',keywords:'river tubing water trails playground bike skills family kids free',url:'longmont.html#dickens-farm-nature-area',cost:'free'},
{name:'Garden Acres Community Park',town:'Longmont',type:'place',category:'Outdoors, Family & Kids',keywords:'park playground recreation family kids outdoor free',url:'longmont.html#garden-acres-community-park',cost:'free'},
{name:'Longmont Ice Pavilion',town:'Longmont',type:'place',category:'Family & Kids, Classes & Experiences',keywords:'ice skating skate seasonal winter roosevelt park family',url:'longmont.html#longmont-ice-pavilion'},
{name:'Longmont Restaurant Week',town:'Longmont',type:'event',category:'Events, Food & Drink',keywords:'restaurant week dining dinner food local restaurants october event',url:'longmont.html#longmont-restaurant-week'},
{name:'Día de Muertos Family Celebration',town:'Longmont',type:'event',category:'Events, Arts & Culture, Family & Kids',keywords:'day of dead dia de muertos family celebration art culture october',url:'longmont.html#dia-de-muertos-family-celebration'},
{name:'ArtWalk on Main',town:'Longmont',type:'event',category:'Events, Arts & Culture, Live Music',keywords:'artwalk art music live music downtown main street annual event',url:'longmont.html#artwalk-on-main'},
{name:'Left Hand Oktoberfest',town:'Longmont',type:'event',category:'Events, Live Music, Food & Drink, Family & Kids',keywords:'oktoberfest live music craft market food trucks family event september',url:'longmont.html#left-hand-oktoberfest'},
{name:'Kit Carson County Carousel & Museum',town:'Burlington',type:'place',category:'History, Family & Kids, Classes & Experiences',keywords:'carousel museum historic attraction family kids ride national historic landmark',url:'burlington.html#kit-carson-county-carousel-museum'},
{name:'Old Town Museum',town:'Burlington',type:'place',category:'History, Family & Kids',keywords:'museum historic buildings history old town family entertainment',url:'burlington.html#old-town-museum'},
{name:'Parmer Park — Spaceship Park',town:'Burlington',type:'place',category:'Outdoors, Family & Kids',keywords:'park rocket spaceship playground splash pad picnic family kids free',url:'burlington.html#parmer-park-spaceship-park',cost:'free'},
{name:'Burlington City Park',town:'Burlington',type:'place',category:'Outdoors, Family & Kids',keywords:'park playground castle swings picnic family kids free',url:'burlington.html#burlington-city-park',cost:'free'},
{name:'The Dish Room',town:'Burlington',type:'business',category:'Food & Drink',keywords:'restaurant dining dinner farm to table food local',url:'burlington.html#the-dish-room'},
{name:'The Blend',town:'Burlington',type:'business',category:'Food & Drink',keywords:'coffee boba tea baked goods cafe drinks',url:'burlington.html#the-blend'},
{name:"Delia's Tacos and More",town:'Burlington',type:'business',category:'Food & Drink',keywords:'tacos mexican food truck breakfast burritos carne asada barbacoa',url:'burlington.html#delias-tacos-and-more'},
{name:"Maria's Mexican Food",town:'Burlington',type:'business',category:'Food & Drink',keywords:'mexican restaurant burritos salsa dinner food',url:'burlington.html#marias-mexican-food'},
{name:'The Cougar Den',town:'Burlington',type:'business',category:'Food & Drink, Movies & Entertainment, Family & Kids',keywords:'food games pool arcade bingo entertainment',url:'burlington.html#the-cougar-den'},
{name:"The Sparrow's Nest Antiques and Collectables",town:'Burlington',type:'business',category:'Shopping',keywords:'antiques collectibles gifts vintage shopping treasure',url:'burlington.html#the-sparrows-nest-antiques-and-collectables'},
{name:'The Shaman Shoppe',town:'Burlington',type:'business',category:'Shopping, Local Makers',keywords:'aromatherapy apothecary handcrafted gifts shopping',url:'burlington.html#the-shaman-shoppe'}
];

window.MKTSearch = (function(){
 const stop=new Set('i a an the and or to in at on for of we want looking find me my our is are do some something take new with where can go get purchase buy day trip colorado'.split(' '));
 const synonyms={bookstore:['book','books','reading'],book:['bookstore','books'],kayak:['kayaking','paddle','paddleboard','water'],kayaking:['kayak','paddleboard','water'],swim:['swimming','water','beach'],swimming:['swim','water','beach'],movie:['movies','cinema','theater','entertainment'],movies:['movie','cinema','theater','entertainment'],rug:['rugs','home','decor','furnishings'],dinner:['restaurant','dining','food'],music:['live','concert'],kids:['family','children'],free:['park','nature']};
 function norm(s){return (s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
 function terms(s){let out=[];norm(s).split(/\s+/).filter(x=>x&&!stop.has(x)).forEach(x=>{out.push(x);(synonyms[x]||[]).forEach(y=>out.push(y))});return [...new Set(out)]}
 function search(query,town,category,cost){let ts=terms(query),tn=norm(town),cat=norm(category),co=norm(cost);return window.MKT_SEARCH_INDEX.map(x=>{let hay=norm([x.name,x.town,x.type,x.category,x.keywords,x.cost].join(' ')),score=0;ts.forEach(t=>{if(norm(x.name).includes(t))score+=8;else if(norm(x.category).includes(t))score+=5;else if(hay.includes(t))score+=2});if(tn){if(norm(x.town).includes(tn))score+=12;else return null}if(cat){if(norm(x.category).includes(cat))score+=8;else return null}if(co){if(norm(x.cost)===co)score+=6;else return null}return score>0?{...x,score}:null}).filter(Boolean).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,24)}
 function installAnchors(){document.querySelectorAll('article.card').forEach(card=>{if(card.id)return;let h=card.querySelector('h3');if(!h)return;let id=norm(h.textContent).replace(/ /g,'-');card.id=id});if(location.hash){let el=document.getElementById(location.hash.slice(1));if(el)setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),50)}}
 return {search,installAnchors};
})();
document.addEventListener('DOMContentLoaded',()=>window.MKTSearch.installAnchors());